export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SIGN_OUT = "SIGN_OUT";
export const REGISTER = "REGISTER";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const GET_FOLLOWERS = "GET_FOLLOWERS";
export const GET_FOLLOWING = "GET_FOLLOWING";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const EDIT_CATEGORY_ERROR = "EDIT_CATEGORY_ERROR";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
